/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
 * Generated on: 20-Apr-2016 03:04:32
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 21
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2015b\extern\include\tmwtypes.h 
 */
#define B_LEN2 21

const real64_T B2[B_LEN2] = {
  -0.001193635497328,  0.01479834550445, -0.02464001456918,  0.03312873086616,
   -0.02979494616203, 0.007869808952784,  0.03444033167313, -0.09122938301045,
     0.1495456218508,  -0.1934130086012,   0.2097155285828,  -0.1934130086012,
     0.1495456218508, -0.09122938301045,  0.03444033167313, 0.007869808952784,
   -0.02979494616203,  0.03312873086616, -0.02464001456918,  0.01479834550445,
  -0.001193635497328
};

int h_hpf[] = {
	 -12,   148, -246,   331,
	-298,    79,  344,  -912,
	1495, -1934, 2097, -1934,
	1495,  -912,  344,    79,
	-298,   331, -246,   148,
	-12
};
