/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
 * Generated on: 20-Apr-2016 01:04:06
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 20
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2015b\extern\include\tmwtypes.h 
 */
//const int B_LEN = 20;
#define B_LEN 20

const real64_T B[B_LEN] = {
   0.008043725579706,-0.0003297346472728, -0.01588101867295, -0.03735102309623,
   -0.04940883148199,  -0.0330928375813,  0.02206106525545,    0.107675742849,
     0.1961046189561,   0.2523907370934,   0.2523907370934,   0.1961046189561,
      0.107675742849,  0.02206106525545,  -0.0330928375813, -0.04940883148199,
   -0.03735102309623, -0.01588101867295,-0.0003297346472728, 0.008043725579706
};

int h[] = {
	  80,   -3, -159,  -374,
	-494, -331,  221,  1077,
	1961, 2524,  2524, 1961,
	1077,  221,  -331, -494,
	-374, -159,-3, 80
};
