/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
 * Generated on: 17-Apr-2016 02:00:31
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2015b\extern\include\tmwtypes.h 
 */
const int FILTER_LENGTH = 11;
const real64_T h_FIR[11] = {
    0.01486394431374,  0.05879446643722,   0.1129357761425,   0.1811323709923,
     0.2323244176855,   0.2533503823823,   0.2323244176855,   0.1811323709923,
     0.1129357761425,  0.05879446643722,  0.01486394431374
};
